development:
  adapter: postgresql
  database: dev_aditup
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: test_aditup
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: production_aditup
  host: localhost
  pool: 5
  timeout: 5000
