# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
#
# Seed Traits
categories = ["Automotive",
"Beauty/Cosmetics Toiletries",
"Business Equipment and Services",
"Children's Audience",
"Collectibles/Gifts",
"Computers/Information Technology",
"Entertainment/Amusement",
"Event",
"Financial Services/Banking",
"Food/Beverage",
"Furniture/Home Furnishings/Appliances",
"Health and Wellness",
"Hospital",
"Household Products/Packaged Goods",
"Institutional/Corporate Image",
"Insurance",
"Lawyer/Legal Services",
"Miscellaneous",
"Not-for-profit",
"Pharmaceuticals",
"Politcal Issues/Campaign Advertising",
"Professional Services",
"Public Service",
"Real Estate",
"Restaurant(including fast food)",
"Retail",
"Schools/Colleges/Universities",
"Sports/Sporting Goods/Games",
"Student",
"Telecommunications/Internet Service",
"Transportation",
"Travel/Tourism",
"Utilities",
"Green/Eco-Friendly"]
categories.each do |category|
  Trait.create(name: category)
end

agencies = ["[wire] stone",
"361 Sports & Event Marketing",
"Access Communications",
"Activa PR",
"Agency.com: San Francisco",
"AgencyAxis",
"AKQA",
"Allison & Partners",
"Alterpop.com",
"Amazon Advertising",
"Ameredia Inc",
"Amsterdam Worldwide",
"Andrea Design Group",
"Antenna Group, Inc.",
"Anthem Worldwide",
"Applied Storytelling",
"Asterix Group",
"Attack",
"ATTIK",
"Baker Street Partners",
"Bakken Creative Co.",
"Barc Integrated Marketing",
"BayCreative",
"BBDO West",
"Binger Catalog Marketing",
"Bravo",
"Brothers By Choice",
"brown+young",
"Buderengel",
"Cahan & Associates",
"Carol H. Williams Advertising",
"Charles Zukow Associates",
"Chase Communications",
"Citigate Cunningham",
"Citizen Group",
"Cohn & Wolfe San Francisco",
"Colsky Media",
"Creative B'stro",
"Criterium Marketing",
"Cuesta Technologies Web Development LLC",
"Cutwater",
"Dae Advertising",
"Danoo, Inc.",
"Davis & Associates",
"DDB California",
"Delivery Agent, Inc.",
"Dial House",
"Diesel Design",
"Direct Partners San Francisco",
"DOJO Partners, LLC",
"Doremus San Francisco",
"Double Fusion",
"Double-Forte",
"Duncan/Channon",
"DWA",
"Ecast Inc.",
"Echo Sports Marketing",
"Edelman",
"Eleven",
"Engage In-Game Advertising",
"Engine Company 1",
"Evolution BUreau",
"Fancy",
"Flashpoint Public Relations",
"Forward Push Media",
"Foster Media",
"Fox & Crow",
"freestyle interactive",
"Freshout",
"Fuseproject, Inc.",
"Geary LSF",
"Gershoni",
"Glodow Nead Communications, LLC",
"Goodby Silverstein & Partners",
"Grey San Francisco",
"Groshelle Communications",
"Grow Marketing",
"Guerilla PR, Inc.",
"Gumas",
"H&L Partners",
"Hadley Media, inc",
"Hagen/Sinclair Research Recruiting, Inc",
"Haggin Marketing",
"Hamilton Ink Publicity & Media Relations",
"HAVAS Worldwide - San Francisco",
"Hawk Media, Inc.",
"Heat",
"Helvetica Creative",
"Hill & Knowlton, Inc.",
"HINT & CO.",
"Horn Group",
"Hub Strategy",
"Hybrid Design",
"IDEO",
"Igor",
"IM Republic - Digital Advertising Agency",
"JAM Public Relations",
"Jamison McKay",
"Jumpstart Automotive Media, Inc.",
"Jungle Communications, Inc.",
"JVST",
"K/F Communications",
"Kadium",
"Kaleidoscope",
"Ketchum West",
"Kiyomura-Ishimoto Associates",
"Landis Communications Inc.",
"Latino Agency",
"Legan Promotions, Inc.",
"Lewis PR",
"Long Productions",
"Luxus Inc",
"M: Metrics",
"Madison, Sproul & Partners",
"Manning Selvage & Lee/San Francisco",
"MarketTools",
"MCorp Consulting",
"MEC San Francisco",
"Mediasmith, Inc.",
"MetaDesign",
"Method, Inc.",
"Mojave Interactive",
"Mortar",
"Moving Brands",
"MWW - San Francisco",
"NextMedia Group",
"Noise 13",
"OMD Latino",
"OMD San Francisco",
"Ootem Advertising",
"Organic, Inc.",
"Ozone Advertiisng, Design + Strategy",
"Page One PR",
"Palmer Advertising",
"PenaBrand",
"Pereira & O'Dell",
"Philippe Becker Design, Inc.",
"Pike & Company",
"PR & Company",
"Propane Studio",
"Questus",
"R/West",
"Rassak Experience",
"Razorfish",
"Reboot Creative + Strategy",
"Red Bricks Media",
"Red Consultancy",
"Redscout",
"Resource",
"Riney",
"Rivet Global",
"Round2 Communications/SF",
"San Francisco 3D Films",
"Sard Verbinnen",
"Schawk San Francisco",
"SHIFT Communications, LLC",
"Signal to Noise",
"SKOW",
"Solem & Associates",
"SolutionSet",
"Sportgenic",
"Stearns Johnson",
"Stratagem Healthcare Communications",
"SutherlandGold Communications",
"Swirl",
"T3",
"Tamotsu Yagi Design",
"Tesser",
"Text 100 Global Public Relations",
"The Blue Shirt Group",
"The Loomis Group, Inc.",
"Theme Co-Op Promotions",
"Thrivepoint",
"THUNDER FACTORY",
"Titan Worldwide",
"Traction",
"Trademark Event Promotions, Inc.",
"TriplePoint",
"TrueBrand, LLC",
"Turning Point Solutions",
"twofifteenmccann",
"Vanderbyl Design",
"Venables Bell & Partners",
"Viewstream, Inc.",
"Volume Inc",
"VSC Consulting",
"WDFA Marketing",
"WeissComm Partners",
"Wheel Media",
"wikreate",
"WorldWalk Media",
"Wunderman San Francisco",
"Y&R California",
"ZAAZ San Francisco",
"Zaudhaus Design"]

agencies.each do |agency|
  Agency.create(:name => agency)
end
